# PDF QR Extractor Configuration
#
# Supported Platform:
#   Ubuntu 20.04 LTS and later
#
# Socket Path
EXTRACTOR_SOCKET_PATH=/opt/pdf-qr-extractor/run/pdf_qr_extractor.sock

# PDF Processing Limits
MAX_PDF_PAGES_FOR_QR_SCAN=2       #Max 10
MAX_PDF_QR_DECODE_KB_SIZE=1000    #Max 1 MB
MAX_QR_DECODE_KB_SIZE=1000        #Max 5 MB

# Performance
WORKER_THREADS=3
REQUEST_TIMEOUT_MS=2500

# Security
ALLOWED_UID=1000

# Logging
LOG_LEVEL=ERROR
#CONSOLE_OUTPUT=TRUE
LOG_SIZE = 100000

LOG_FILE = /tmp/extractor.log
