# PDF QR Extractor Configuration
#
# Supported Platform:
#   Ubuntu 20.04 LTS and later
#
# Socket Path
EXTRACTOR_SOCKET_PATH=/opt/pdf-qr-extractor/run/pdf_qr_extractor.sock

# PDF Processing Limits
MAX_PDF_PAGES_FOR_QR_SCAN=2       #Max 10
MAX_PDF_QR_DECODE_KB_SIZE=1000    #Max 1 MB
MAX_QR_DECODE_KB_SIZE=1000        #Max 5 MB

# Performance
WORKER_THREADS=4
REQUEST_TIMEOUT_MS=3000

# Security (need to be updated as per the user created on the end user machine)
ALLOWED_UID=997

# Logging (NOT IN USE as on 26/02/2026)
LOG_LEVEL=INFO
CONSOLE_OUTPUT=false
